package com.xyz.SearchFunctionalityTest;

import com.xyz.Report.AutoGeneratedReport;
import static com.xyz.pageUtilities.YamlFileReader.getYamlData;
import static com.xyz.capabilities.Capabilities.*;
import java.io.FileNotFoundException;
import java.net.MalformedURLException;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import com.xyz.actionPages.SearchFunctionality;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidElement;
import java.io.IOException;

/**
 *
 * @author Saksham Varshney
 */
public class SearchFunctionalityTest extends AutoGeneratedReport
{
    public AndroidDriver<AndroidElement> driver;
    SearchFunctionality obj;
    
    @BeforeClass
    public void setup() throws FileNotFoundException, MalformedURLException
    {
        String deviceName= getYamlData("deviceName");
        String platformName= getYamlData("platformName");
        String appPackage= getYamlData("appPackage.flipkart");
        String appActivity= getYamlData("appActivity.flipkart.homepage");
        String appiumUrl= getYamlData("appiumUrl");
        
        driver= setcapabilitiesMethod(deviceName, platformName, appPackage, appActivity, appiumUrl);
        obj= new SearchFunctionality(driver);
    }
    
    @Test(priority=0, description="Click on Homepage Search Box")
    public void clickOnSearchBar() throws IOException
    {
        test = extent.createTest("Test case- 01", "Click on Homepage Search Box");
        obj.clickOnHomepageSearchBox();
        test.pass("Passed: Clicked on Homepage Search box");
    }
}